// Code generated by "stringer -type=DeviceStatus"; DO NOT EDIT.

package common

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Idle-9223372036854775806]
	_ = x[Error-9223372036854775807]
}

const _DeviceStatus_name = "IdleError"

var _DeviceStatus_index = [...]uint8{0, 4, 9}

func (i DeviceStatus) String() string {
	i -= 9223372036854775806
	if i < 0 || i >= DeviceStatus(len(_DeviceStatus_index)-1) {
		return "DeviceStatus(" + strconv.FormatInt(int64(i+9223372036854775806), 10) + ")"
	}
	return _DeviceStatus_name[_DeviceStatus_index[i]:_DeviceStatus_index[i+1]]
}
