// Code generated by "stringer -type=NodeStatus"; DO NOT EDIT.

package common

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Offline-0]
	_ = x[Online-1]
}

const _NodeStatus_name = "OfflineOnline"

var _NodeStatus_index = [...]uint8{0, 7, 13}

func (i NodeStatus) String() string {
	if i >= NodeStatus(len(_NodeStatus_index)-1) {
		return "NodeStatus(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _NodeStatus_name[_NodeStatus_index[i]:_NodeStatus_index[i+1]]
}
