// Code generated by "stringer -type=UCode"; DO NOT EDIT.

package common

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[UCodeDatabase-1]
}

const _UCode_name = "UCodeDatabase"

var _UCode_index = [...]uint8{0, 13}

func (i UCode) String() string {
	i -= 1
	if i >= UCode(len(_UCode_index)-1) {
		return "UCode(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _UCode_name[_UCode_index[i]:_UCode_index[i+1]]
}
